### ISSUE TITLE
Requests processor for http-to-http and http-to-dubbo

### ISSUE THREAD

**Issue by williamfeng323** [dubbogo/dubbo-go-proxy#19]
**What would you like to be added**:
As a developer, I want to create requests processors to process and map the http-to-http and http-to-dubbo requests. 
**Why is this needed**:

**Comment by williamfeng323** [comment]
@cityiron @zhangshen023 
关于route有两个问题需要跟讨论下，
1. dubbo-go-proxy是以api gateway为主，route的config是否可以以api config中的设置为主？是否可以把现在conf.yml 中route_config那部分忽略？
2. api_filter和router_filter部分功能有重合，我是否可以统一在router_filter中实现？

**Comment by cityiron** [comment]
I agree your questions, we must support api config first, api model is core. The router in project is not for api model, is used for request protocol transfer.
