### ISSUE TITLE
Improved remove dubbogo config file

### ISSUE THREAD

**Issue by cityiron** [dubbogo/dubbo-go-proxy#3]
**What would you like to be added**:
Remove dubbogo's client.yaml and log.yaml configuration. 
Use proxy configuration to adapter the dubbogo consumer.

**Why is this needed**:
Dubbogo Proxy is project not juet for dubbogo, it need low coupling.

**Comment by DogBaoBao** [comment]
First time, it must need params like: register, timeout, group, version.., consider the following: multi register exist.

**Comment by DogBaoBao** [comment]
@zhangshen023

**Comment by zhangshen023** [comment]
WIP @DogBaoBao
