### ISSUE TITLE
Add api load

### ISSUE THREAD

**Issue by cityiron** [dubbogo/dubbo-go-proxy#7]
**What would you like to be added**:
Api config can load from e.g: api_config.yaml, or config center like nacos.

**Why is this needed**:
Gateway must can control api, so api config load from remote or local.

**Comment by DogBaoBao** [comment]
@williamfeng323

**Comment by yqxu** [comment]
@williamfeng323  TieChen told me you will define a metadata of Dubbo api . In my issue I need a metadata of http api also. I prefer we can have a talk about this.      dingding : km6rfl0

**Comment by oaoit** [comment]
get

**Comment by DogBaoBao** [comment]
Duplicate of #17
