### ISSUE TITLE
api_config.yaml中使用通用形式(dubbo request universality)无法调用dubbo

### ISSUE THREAD

**Issue by FeiYing9** [dubbogo/dubbo-go-proxy#84]
**What happened**:

参照`sample/dubbogo/proxy/api_config.yaml`里的配置和`docs/sample/dubbo-universality.md`里的方式，并没有返回期望的POST结果

**What you expected to happen**:
- Request

```bash
curl host:port/api/v1/test-dubbo/UserProvider/com.ic.user.UserProvider?method=GetUserByName&group=test&version=1.0.0 -X POST -d '{"types":["java.lang.String"],"values":"tc"}' --header "Content-Type: application/json"
```

- Response

```json
{
    "age": 18,
    "code": 1,
    "iD": "0001",
    "name": "tc"
}
```
    
**How to reproduce it (as minimally and precisely as possible)**:
1. 使用2020/12/22最新的develop代码`32fda76a` 编译 `sample/dubbogo/server/app`和`cmd/proxy/`
2. 使用`sample/dubbogo/server/config/`的配置启动server
3. 使用`sample/dubbogo/proxy/`的配置启动proxy
4. 所有配置中仅仅修改了zk的真实地址
5. 使用Get请求发送到`127.0.0.1:8888/api/v1/test-dubbo/user?name=tc`返回期望结果
6. 使用POST请求发送common请求，返回404

**Anything else we need to know?**:
1. 上述server和proxy运行在golang的pod中
2. 使用的镜像为docker hub上的`golang:1.14-stretch`, 即: go version go1.14.6 linux/amd64
3. server与proxy均使用该pod完成编译，再分别运行二进制文件
4. 运行结果如下:

```bash
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

# uname -a
Linux my-hostname-8c9f6b5b6-t8jwx 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 GNU/Linux

# ps -ef
UID         PID   PPID  C STIME TTY          TIME CMD
root          1      0  0 Dec15 ?        00:00:00 tail -f /etc/hosts
root       7098      0  0 09:44 ?        00:00:00 bash
root       7918   7098  0 09:49 ?        00:00:00 bash server-start.sh
root       7919   7918  0 09:49 ?        00:00:07 /go/bin/dubbo-proxy/dubbo-go-server-proxy
root       7936   7098  0 09:49 ?        00:00:00 bash proxy.sh
root       7937   7936  0 09:49 ?        00:00:06 /go/bin/dubbo-proxy/dubbo-go-proxy start -c /go/src/dubbo-proxy/sample/dubbogo/proxy/conf.yaml -a /go/src/dubbo-proxy/sample/dubbogo/proxy/api_config.yaml

# curl -i  http://127.0.0.1:8888/api/v1/test-dubbo/user?name=tc
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Tue, 22 Dec 2020 01:58:27 GMT
Content-Length: 43

{"age":18,"code":1,"iD":"0001","name":"tc"}

# curl -i localhost:8888/api/v1/test-dubbo/UserProvider/com.ic.user.UserProvider?method=GetUserByName&group=test&version=1.0.0 -X POST -d '{"types":["java.lang.String"],"values":"tc"}' --header "Content-Type: application/json"
[1] 7987
[2] 7988
bash: -X: command not found
[2]+  Done                    group=test
root@golang-ecp-ewell-8c9f6b5b6-t8jwx:/go# HTTP/1.1 404 Not Found
Date: Tue, 22 Dec 2020 01:59:30 GMT
Content-Length: 18
Content-Type: text/plain; charset=utf-8

404 page not found
[1]+  Done                    curl -i localhost:8888/api/v1/test-dubbo/UserProvider/com.ic.user.UserProvider?method=GetUserByName
```

**Comment by FeiYing9** [comment]
另外，发现`docs/sample/dubbogo-body.md`中的例子也是错误的，
- Request

```bash
curl host:port/api/v1/test-dubbo/user -X POST -d '{"name":"tiecheng","id":"0002","age":18}' --header "Content-Type: application/json"
```
不管更新name还是id, 永远返回的

```json
{
    "message": "data is exist"
}
```

应该使用这个请求：id改为`int`类型

```bash
# curl -i localhost:8888/api/v1/test-dubbo/user -X POST -d '{"name":"tiecheng1","id":1002,"age":18}' --header "Content-Type: application/json"
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Tue, 22 Dec 2020 02:50:36 GMT
Content-Length: 0

# curl -i localhost:8888/api/v1/test-dubbo/user?name=tiecheng1                                                                
HTTP/1.1 200 OK
Content-Type: application/json;charset=UTF-8
Date: Tue, 22 Dec 2020 02:51:18 GMT
Content-Length: 50

{"age":18,"code":0,"iD":"1002","name":"tiecheng1"}
```

**Comment by FeiYing9** [comment]
发现官方好像并没有维护sample中的配置或源码，有些配置项明显是错误的

**Comment by cityiron** [comment]
> 发现官方好像并没有维护sample中的配置或源码，有些配置项明显是错误的

目前的 samples 参考 https://github.com/dubbogo/dubbo-go-proxy-samples，文档这两天会更新

**Comment by cityiron** [comment]
> 发现官方好像并没有维护sample中的配置或源码，有些配置项明显是错误的

The more info in our testing work result [https://github.com/dubbogo/proxy-community/blob/master/test/test-manual.md](https://github.com/dubbogo/proxy-community/blob/master/test/test-manual.md)

**Comment by FeiYing9** [comment]
> 
> 
> > 发现官方好像并没有维护sample中的配置或源码，有些配置项明显是错误的
> 
> 目前最新的 samples 参考 https://github.com/dubbogo/dubbo-go-proxy-samples，文档这两天会更新

文档的出处会不会太多了？

* https://github.com/dubbogo/proxy-community/blob/master/test/test-manual.md

* https://github.com/dubbogo/dubbo-go-proxy-samples

* https://github.com/dubbogo/dubbo-go-proxy/docs/sample

是否应该维护一处文档，其他地方进行跳转更好？  不然都不知道改看哪一篇了

**Comment by cityiron** [comment]
> > > 发现官方好像并没有维护sample中的配置或源码，有些配置项明显是错误的
> > 
> > 
> > 目前最新的 samples 参考 [https://github.com/dubbogo/dubbo-go-proxy-samples，文档这两天会更新](https://github.com/dubbogo/dubbo-go-proxy-samples%EF%BC%8C%E6%96%87%E6%A1%A3%E8%BF%99%E4%B8%A4%E5%A4%A9%E4%BC%9A%E6%9B%B4%E6%96%B0)
> 
> 文档的出处会不会太多了？
> 
> * https://github.com/dubbogo/proxy-community/blob/master/test/test-manual.md
> * https://github.com/dubbogo/dubbo-go-proxy-samples
> * https://github.com/dubbogo/dubbo-go-proxy/docs/sample
> 
> 是否应该维护一处文档，其他地方进行跳转更好？ 不然都不知道改看哪一篇了

感谢提议，计划文档都会维护到项目的docs下，在其它地方的会在docs下放链接的

**Comment by FeiYing9** [comment]
又根据新文档改了一下api_config.yaml，不知道是不是自身配置的问题，还是出现了最初描述的问题。。。哈哈

这个文档中的api_config.yaml可能也是历史版本，` interface: "com.dubbogo.proxy.UserService"`与server中的配置`interface: "com.ic.user.UserProvider"`都不一致

除了`GET /api/v1/test-dubbo/user?name=tc`能通，其他好几个都通不了。。

问题一：
```bash
# curl -i -X POST -d '{"types":["string"],"values":"tc"}' --header "Content-Type: application/json" localhost:8888/api/v1/test-dubbo/UserProvider/com.ikurento.user.User?method=GetUserByName&group=test&version=1.0.0

HTTP/1.1 503 Service Unavailable
Content-Type: application/json;charset=UTF-8
Date: Thu, 24 Dec 2020 03:01:11 GMT
Content-Length: 52

{"message":"Query parameter [group] does not exist"}
这里如果把method放后面，报错method does not exist，挪到第一个参数后一直会报错group not exist
```
问题二：
```bash
# curl -i  localhost:8888/api/v1/test-dubbo/user-add -X POST -d '{"name":"lisi","id":"1001","age":18}' --header "Content-Type: application/json"
HTTP/1.1 503 Service Unavailable
Content-Type: application/json;charset=UTF-8
Date: Thu, 24 Dec 2020 03:03:09 GMT
Content-Length: 23

{"message":"add error"}
使用之前的user-add接口，报错add error, 看看server的源码，也想不通为啥会error
```
server会有一大段报错，最近刚刚接触dubbo和dubbo-go，排查不了问题

**Comment by cityiron** [comment]
> 又根据新文档改了一下api_config.yaml，不知道是不是自身配置的问题，还是出现了最初描述的问题。。。哈哈
> 
> 这个文档中的api_config.yaml可能也是历史版本，` interface: "com.dubbogo.proxy.UserService"`与server中的配置`interface: "com.ic.user.UserProvider"`都不一致
> 
> 除了`GET /api/v1/test-dubbo/user?name=tc`能通，其他好几个都通不了。。
> 
> 问题一：
> 
> ```shell
> # curl -i -X POST -d '{"types":["string"],"values":"tc"}' --header "Content-Type: application/json" localhost:8888/api/v1/test-dubbo/UserProvider/com.ikurento.user.User?method=GetUserByName&group=test&version=1.0.0
> 
> HTTP/1.1 503 Service Unavailable
> Content-Type: application/json;charset=UTF-8
> Date: Thu, 24 Dec 2020 03:01:11 GMT
> Content-Length: 52
> 
> {"message":"Query parameter [group] does not exist"}
> 这里如果把method放后面，报错method does not exist，挪到第一个参数后一直会报错group not exist
> ```
> 
> 问题二：
> 
> ```shell
> # curl -i  localhost:8888/api/v1/test-dubbo/user-add -X POST -d '{"name":"lisi","id":"1001","age":18}' --header "Content-Type: application/json"
> HTTP/1.1 503 Service Unavailable
> Content-Type: application/json;charset=UTF-8
> Date: Thu, 24 Dec 2020 03:03:09 GMT
> Content-Length: 23
> 
> {"message":"add error"}
> 使用之前的user-add接口，报错add error, 看看server的源码，也想不通为啥会error
> ```
> 
> server会有一大段报错，最近刚刚接触dubbo和dubbo-go，排查不了问题

因为 server samples项目里面和proxy里面是不一样的，所以调不通了，我的docs是针对 samples 的例子。这两天我们会把所有的文档和 proxy/samples 里面对应上，把之前proxy-sampels里面的例子都挪过来
